<?php
//require '../../vendor/autoload.php';
use phpMailer\PHPMailer\PHPMailer;
use phpMailer\PHPMailer\Exception;

require 'generatePassword.php';


require 'database.php'; // Make sure to have the database connection
$file_target = '../SQL/users.sql';


if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    if (isset($_POST['email'])) {
        $email = trim($_POST['email']);

        // Sanitize the email to avoid SQL injection (prepare the query properly)
        $stmt = $pdo->prepare("SELECT COUNT(*) FROM users WHERE username = :email");
        $stmt->execute(['email' => $email]);

        // If the count is greater than 0, it means the email exists in the database
        if ($stmt->fetchColumn() > 0) {
            $_SESSION['email_error'] = 'Email already exists. Please use a different email.';
        } else {
            // Collect form inputs and sanitize them
            $firstName = trim($_POST['first_name']);
            $lastName = trim($_POST['last_name']);
            // Assuming the password is generated by some custom function
            $password = generatePassword();  // Make sure this function is defined somewhere

            // Hash the password using SHA-512
            $hashedPassword = hash('sha512', $password);

            // Insert the user into the database
            $stmt = $pdo->prepare('
            INSERT INTO users (username, firstName, lastName, password, active) 
            VALUES (:username, :firstName, :lastName, :password, 0)
            ');

            // Execute the query with the appropriate values
            $stmt->execute([
                'username' => $email,  // Use email as the username
                'firstName' => $firstName,
                'lastName' => $lastName,
                'password' => $hashedPassword,
            ]);

            // If insertion was successful
            if ($stmt->rowCount() > 0) {

                $query = 'INSERT INTO users (username, firstName, lastName, password, active) 
            VALUES (\':username\', \':firstName\', \':lastName\', \':password\', 0)';

                // Replace values manually in the SQL string
                $insertSQL = str_replace(
                    [':username', ':firstName', ':lastName', ':password'],
                    [$email, $firstName, $lastName, $hashedPassword],
                    $query
                );
                if (file_put_contents($file_target, $insertSQL . PHP_EOL, FILE_APPEND)) {
                } else {
                    echo "Error saving the INSERT statement.";
                }

                // Set cookies for the user (e.g., session persistence)
                setcookie('email', $email, time() + 3600, '/'); // 1 hour duration
                setcookie('password', $password, time() + 3600, '/'); // 1 hour duration

                // Redirect to a thank you page after successful registration
                header('Location: thankYouRegister.php');
                exit();
            } else {
                $_SESSION['email_error'] = 'There was an error during registration. Please try again later.';
            }
        }

    } else {
        $_SESSION['email_error'] = 'Email is required!';
    }

} else {
    //   echo 'Invalid request method!';  // Invalid request method
}

?>